[package]
name = "wl-gammarelay-rs"
version = "0.1.0"
authors = ["Max Verevkin <maxxverrr@gmail.com>"]
edition = "2021"
description = "A simple program that provides DBus interface to control display temperature and brightness under wayland without flickering"
repository = "https://github.com/MaxVerevkin/wl-gammarelay-rs"
license = "GPL-3.0-only"
keywords = ["redshift", "gammastep", "wayland", "night-mode"]

[dependencies]
anyhow = "1.0"
memmap = "0.7"
wayland-client = "0.30.0-alpha3"
wayland-protocols = { version = "0.30.0-alpha3", features = ["unstable_protocols", "client"] }
tokio = { version = "1.15", features = ["full"] }
zbus = { version = "2.0", features = ["tokio"] }
